### ISSUE TITLE
Feature Request: React (and Vue) version/support?

### ISSUE THREAD

**Issue by amharris** [AndrewJBateman/ionic-select-searchbar#12]
I've just come across this project, as I'm looking for a plugin that effectively offers the `IonSearchbar` interface but with the underlying functionality of acting as `IonSelect` when selecting a result and then showing it afterwards but I'm working with an Ionic 5 React project.

It would be good to be provided as a multi-framework plugin that works with Ionic Angular, React (and Vue, now that it's available and stable).

I may have to roll my own solution in the meantime but would happily contribute to this in any way I can, (despite this being my first use of React, TypeScript and full 'native' app (not webview bits) in a project all at once) if it means I can adapt this work to React.

**Comment by AndrewJBateman** [comment]
I didn't create the IonSelect, I just used it:

**Comment by AndrewJBateman** [comment]
I didn't create the IonSelect, I just used it:

**Comment by amharris** [comment]
Hi @AndrewJBateman 

Thanks for getting back to me, despite the time it's been.

To clarify, I understand that you didn't create the core component `IonSelect` but leveraged it as a part of your component.
What I was requesting is if you could look at making a React or Vue version of your implementation, now that Ionic has React and Vue offerings.

Edit: Per my other issue/request, now that I think I've correctly understood what you mean, it's less of an issue, but if you have the time at any point, I'd still be keen to see how you approach the implementation with React/Vue, if at all possible.
Ionic Selectable mentions 'Vanilla JS', as well as Angular, so I don't know how easy it would be to build around the Vanilla JS copy to achieve that.  Plus, I'm pretty sure that "Other frameworks support is coming!!!" message has been there for some time.  Perhaps I'll have to get my hands dirty!
